/*
 * FerroChart — C/C++ FFI Header (auto-generated by cbindgen)
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2025 Robert Krick
 *
 * Usage:
 *   1. Link against libferrochart_ffi.so / .dylib / .dll / .a
 *   2. Include this header
 *   3. See docs/integration/c-cpp.md for examples
 */


#ifndef FERROCHART_H
#define FERROCHART_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque chart handle exposed to C.
 *
 * Callers must treat this as a pointer-sized opaque type.
 * Create with [`fc_chart_create`], destroy with [`fc_chart_destroy`].
 */
typedef struct FcChart FcChart;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new chart handle with default configuration.
 *
 * Returns a heap-allocated handle. The caller owns this handle and **must**
 * call [`fc_chart_destroy`] to free it.
 */
struct FcChart *fc_chart_create(void);

/**
 * Destroy a chart handle and free its memory.
 *
 * # Safety
 *
 * `handle` must be a valid pointer returned by [`fc_chart_create`], or null.
 * After this call the pointer is dangling and must not be used again.
 */
void fc_chart_destroy(struct FcChart *handle);

/**
 * Set OHLCV data from parallel C arrays.
 *
 * All arrays must have exactly `len` elements.
 *
 * # Safety
 *
 * All pointers must be valid and point to arrays of at least `len` elements.
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_data(struct FcChart *handle,
                       const int64_t *timestamps,
                       const double *open,
                       const double *high,
                       const double *low,
                       const double *close,
                       const double *volume,
                       uintptr_t len);

/**
 * Set OHLCV data from a JSON string.
 *
 * Expected format: `[{"timestamp":…,"open":…,"high":…,"low":…,"close":…,"volume":…}, …]`
 *
 * Returns 0 on success, -1 on parse error.
 *
 * # Safety
 *
 * `handle` must be valid. `json` must be a valid null-terminated UTF-8 string.
 */
int32_t fc_chart_set_data_json(struct FcChart *handle,
                               const char *json);

/**
 * Set chart dimensions in pixels.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_size(struct FcChart *handle, double width, double height);

/**
 * Set the chart type.
 *
 * Supported values: `"candlestick"`, `"heikin_ashi"`, `"ohlc"`, `"line"`,
 * `"area"`, `"renko"`, `"point_figure"`.
 *
 * Returns 0 on success, -1 on unknown type.
 *
 * # Safety
 *
 * `handle` must be valid. `name` must be a valid null-terminated UTF-8 string.
 */
int32_t fc_chart_set_type(struct FcChart *handle, const char *name);

/**
 * Set Renko brick size. Only effective when chart type is `"renko"`.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_renko_brick_size(struct FcChart *handle, double brick_size);

/**
 * Set Point & Figure parameters.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_pf_config(struct FcChart *handle, double box_size, uint32_t reversal);

/**
 * Apply dark theme colors.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_theme_dark(struct FcChart *handle);

/**
 * Apply light theme colors.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_theme_light(struct FcChart *handle);

/**
 * Enable or disable logarithmic Y-axis.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_set_log_scale(struct FcChart *handle, bool enabled);

/**
 * Apply a full JSON configuration.
 *
 * Returns 0 on success, -1 on parse error.
 *
 * # Safety
 *
 * `handle` must be valid. `json` must be a valid null-terminated UTF-8 string.
 */
int32_t fc_chart_set_config_json(struct FcChart *handle, const char *json);

/**
 * Add a technical indicator by name.
 *
 * Supported names: `"sma"`, `"ema"`, `"bollinger"`, `"rsi"`, `"macd"`,
 * `"atr"`, `"obv"`, `"stochastic"`, `"williams_r"`, `"cci"`, `"adx"`,
 * `"donchian"`, `"keltner"`, `"parabolic_sar"`, `"supertrend"`,
 * `"ichimoku"`, `"session_vwap"`, `"volume_sma"`.
 *
 * `period` is the look-back window (ignored for indicators with fixed params).
 *
 * Returns 0 on success, -1 on unknown indicator name.
 *
 * # Safety
 *
 * `handle` must be valid. `name` must be a valid null-terminated UTF-8 string.
 */
int32_t fc_chart_add_indicator(struct FcChart *handle, const char *name, uintptr_t period);

/**
 * Remove all indicators.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_clear_indicators(struct FcChart *handle);

/**
 * Add a marker (buy/sell signal, label) at a specific bar.
 *
 * `shape`: 0 = arrow up, 1 = arrow down, 2 = circle, 3 = diamond.
 * `position`: 0 = above bar, 1 = below bar.
 *
 * # Safety
 *
 * `handle` must be valid. `label` must be a valid null-terminated UTF-8 string
 * (or null for no label).
 */
void fc_chart_add_marker(struct FcChart *handle,
                         uintptr_t bar_index,
                         uint32_t shape,
                         uint32_t position,
                         uint8_t r,
                         uint8_t g,
                         uint8_t b,
                         const char *label);

/**
 * Remove all markers.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_clear_markers(struct FcChart *handle);

/**
 * Import annotations from a JSON string.
 *
 * Returns 0 on success, -1 on parse error.
 *
 * # Safety
 *
 * `handle` must be valid. `json` must be a valid null-terminated UTF-8 string.
 */
int32_t fc_chart_import_annotations(struct FcChart *handle, const char *json);

/**
 * Export annotations as a JSON string.
 *
 * Returns a heap-allocated null-terminated UTF-8 string. The caller must free
 * it with [`fc_string_free`].
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
char *fc_chart_export_annotations(const struct FcChart *handle);

/**
 * Remove all annotations.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
void fc_chart_clear_annotations(struct FcChart *handle);

/**
 * Render the chart to an SVG string.
 *
 * Returns a heap-allocated null-terminated UTF-8 string containing the SVG.
 * The caller must free it with [`fc_string_free`].
 *
 * Returns null if there is no data set.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
char *fc_chart_render_svg(const struct FcChart *handle);

/**
 * Return the number of OHLCV bars currently loaded.
 *
 * # Safety
 *
 * `handle` must be a valid `FcChart` pointer.
 */
uintptr_t fc_chart_bar_count(const struct FcChart *handle);

/**
 * Free a string previously returned by this library.
 *
 * # Safety
 *
 * `s` must be a pointer returned by an `fc_*` function that returns
 * `*mut c_char`, or null.
 */
void fc_string_free(char *s);

/**
 * Return the library version as a static string.
 *
 * The returned pointer is valid for the lifetime of the library and must NOT
 * be freed by the caller.
 */
const char *fc_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FERROCHART_H */
